<a href="https://colab.research.google.com/github/renatamontanhana/-Dicas_e_Truques_de_Ciencia_de_Dados/blob/main/M4A18_NumPy_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTK4gQ9nhwHHaSXMHpeggWg7twwMCgb877smkRmtkmDeDoGF9Z6&usqp=CAU)

# <font color='BLUE'>Cientista de Dados na Prática </font>

# <font color='GREEN'>Módulo 4 - Análise Exploratória dos Dados</font>

### <font color='GREY'> Numpy - Manipulando arquivos Multidimensionais </font>



# Numpy - Análise de Dados  


<p> Simbóra aprender a trabalhar coma biblioteca Numpy.


In [ ]:
# Importando a biblioteca numpy
import numpy as np

In [ ]:
# Criando um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [ ]:
type(one_dim)

numpy.ndarray

In [ ]:
# Imprimindo um array.
one_dim.ndim

1

In [ ]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [ ]:
# Imprimindo o array
two_dim.ndim

2

In [ ]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((5,2))

array([[0.19233105, 0.74493137],
       [0.92555622, 0.91154292],
       [0.68502475, 0.82781904],
       [0.0725651 , 0.56342071],
       [0.08208054, 0.11861287]])

In [ ]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5.
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# cria um array linear de 0 a 2 de no máximo 9 elementos.
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Cria um array de valores zero.
# Cria um array com 3 linhas e 4 dimensões.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Arrays x Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos
- Arrays Numpy considera todos os elementos de tipos distintos como strings


In [ ]:
# Criando uma lista em Python.
lista = [1,2,3]

In [ ]:
lista

[1, 2, 3]

In [ ]:
type(lista)

list

In [ ]:
# Multiplicar valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
# Transforme a variável lista em um array Numpy
lista = np.array(lista)

In [ ]:
# Imprimindo o tipo do objeto.
type(lista)

numpy.ndarray

In [ ]:
# Multiplicando cada elemento por 2.
lista * 2

array([2, 4, 6])

In [ ]:
# Calcular IMC de pessoas.
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [ ]:
# Faz o calculo usando as listas
pesos / altura ** 2

In [ ]:
# Transforme isso em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [ ]:
# Imprime o calculo de cada valor
pesos / altura **2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [ ]:
# Arrays Numpy armazena elementos como strins quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [ ]:
a

array(['1', '3', 'Casa', 'True'], dtype='<U21')

# Métodos e Atributos Úteis

In [ ]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Retorna a forma do array no formato linhas e colunas.
two_dim.shape

(2, 3)

In [ ]:
# Retorna a quantidade de dimensões.
two_dim.ndim

2

In [ ]:
# Imprimindo o valor máximo do array.
two_dim.max()

6

In [ ]:
# Imprimindo o valor mínimo.
two_dim.min()

1

In [ ]:
# Imprimindo o valor médio.
two_dim.mean()

3.5

In [ ]:
# Imprimindo o desvio padrão.
two_dim.std()

1.707825127659933

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
two_dim.dtype

dtype('int64')

In [ ]:
two_dim.size

6

In [ ]:
# mostra o compromento em bytes
two_dim.itemsize

8

In [ ]:
# Somando todos os elementos do array.
two_dim.sum()

21

#  Transformando Arrays

In [ ]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Gera a Transposta da Matriz (Linha -> coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Transforma em uma matriz de uma linha.
# È muito comum em bibliotecas como scikit-learn e Keras
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
tree = np.random.random((5,3))

In [ ]:
tree.shape

(5, 3)

In [ ]:
tree

array([[0.00861223, 0.46359529, 0.69479254],
       [0.09758477, 0.34114376, 0.23348775],
       [0.46417097, 0.86067084, 0.81351807],
       [0.58064573, 0.8219981 , 0.89291013],
       [0.52138267, 0.78570493, 0.60765229]])

In [ ]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[0.00861223, 0.46359529, 0.69479254, 0.09758477, 0.34114376],
       [0.23348775, 0.46417097, 0.86067084, 0.81351807, 0.58064573],
       [0.8219981 , 0.89291013, 0.52138267, 0.78570493, 0.60765229]])

In [ ]:
tree.reshape(-1)

array([0.00861223, 0.46359529, 0.69479254, 0.09758477, 0.34114376,
       0.23348775, 0.46417097, 0.86067084, 0.81351807, 0.58064573,
       0.8219981 , 0.89291013, 0.52138267, 0.78570493, 0.60765229])

In [ ]:
t=tree.reshape(1,15)
t

array([[0.00861223, 0.46359529, 0.69479254, 0.09758477, 0.34114376,
        0.23348775, 0.46417097, 0.86067084, 0.81351807, 0.58064573,
        0.8219981 , 0.89291013, 0.52138267, 0.78570493, 0.60765229]])

In [ ]:
t

array([[0.00861223, 0.46359529, 0.69479254, 0.09758477, 0.34114376,
        0.23348775, 0.46417097, 0.86067084, 0.81351807, 0.58064573,
        0.8219981 , 0.89291013, 0.52138267, 0.78570493, 0.60765229]])

In [ ]:
t.shape

(1, 15)

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Adicionando elementos a um array.
two_dim = np.insert(two_dim,        0,10)

In [ ]:
# Transforma em um array de uma linha.
two_dim

array([10,  1,  2,  3,  4,  5,  6])

In [ ]:
# Apagando o elemento da primeira posição do array.
two_dim = np.delete(two_dim,[0])

In [ ]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",two_dim, delimiter=',')

# Acessando Dimensões no Array

In [ ]:
# Importando o Numpy
import numpy as np

In [ ]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

In [ ]:
my_array

array([[0.56715556, 0.23390171],
       [0.89046411, 0.67322581],
       [0.09946899, 0.91841506],
       [0.92693097, 0.37160645],
       [0.69673146, 0.40471092],
       [0.91471533, 0.72712869],
       [0.4481451 , 0.83250786],
       [0.36905022, 0.86572517],
       [0.30121807, 0.0870732 ],
       [0.77568458, 0.99060188]])

In [ ]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

array([0.56715556, 0.23390171])

In [ ]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

0.5671555589799209

In [ ]:
# Primeiro elemento da coluna 1
my_array[0][1]

0.23390171073958133

In [ ]:
# Segundo elemento da coluna 1
my_array[1][1]

0.6732258136614971

In [ ]:
my_array

array([[0.56715556, 0.23390171],
       [0.89046411, 0.67322581],
       [0.09946899, 0.91841506],
       [0.92693097, 0.37160645],
       [0.69673146, 0.40471092],
       [0.91471533, 0.72712869],
       [0.4481451 , 0.83250786],
       [0.36905022, 0.86572517],
       [0.30121807, 0.0870732 ],
       [0.77568458, 0.99060188]])

In [ ]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

array([0.23390171, 0.67322581, 0.91841506])

In [ ]:
# Imprime todas as linhas da coluna 2 * 10
my_array[:,1] * 10

array([2.33901711, 6.73225814, 9.18415063, 3.71606451, 4.04710923,
       7.27128687, 8.32507864, 8.65725175, 0.87073198, 9.90601884])

In [ ]:
# Comparação retorna indices
my_array > 0.50

array([[ True, False],
       [ True,  True],
       [False,  True],
       [ True, False],
       [ True, False],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False, False],
       [ True,  True]])

In [ ]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([0.56715556, 0.89046411, 0.67322581, 0.91841506, 0.92693097,
       0.69673146, 0.91471533, 0.72712869, 0.83250786, 0.86572517,
       0.77568458, 0.99060188])

# Trabalhando com Valores Missing

* **Missing Values** são valores faltantes em colunas, esses podem ser oriundos de falhas em cargas de dados, falhas em crawlers ou até mesmo corrupção de dados.

* Missing Values podem ser um problema em várias situações, como por exemplo, algoritmos de machine learning que não trabalham bem com dados faltantes.

* Estes também podem atrapalhar resultados de análises.

* Vamos aprender como encontrar missing values na base de dados e como manipular esses valores.

In [ ]:
import matplotlib


import pandas as pd
arquivo = 'house.csv'
dataset = pd.read_csv(arquivo, sep=',', header=0)

In [ ]:
dataset.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0       3.0       1.00         1180   
1  6414100192  20141209T000000  538000.0       3.0       2.25         2570   
2  5631500400  20150225T000000  180000.0       2.0       1.00          770   
3  2487200875  20141209T000000  604000.0       4.0       3.00         1960   
4  1954400510  20150218T000000  510000.0       3.0       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [ ]:
# Consultando linhas com valores faltantes.
dataset.isnull().sum()

id               0
date             0
price            0
bedrooms         4
bathrooms        0
sqft_living      0
sqft_lot         0
floors           1
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [ ]:
#Com este comando removemos todas as linhas onde tenha pela menos um registro faltante em algum atributo.
dataset.dropna(inplace=True)

In [ ]:
# É possível ainda, remover somente linhas que estejam com valores faltantes em todas as colunas, veja:
dataset.dropna(how='all', inplace=True)

In [ ]:
#preenche com a media dos valores da coluns floors os values null
dataset['floors'].fillna(dataset['floors'].mean(), inplace=True)

In [ ]:
#preenche com 1 os values null da coluna bedrooms
dataset['bedrooms'].fillna(1, inplace=True)

In [ ]:
dataset.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

# Visualização Gráfica - Extraindo Insights

* Vamos agora trabalhar com um tipo de gráfico muito interessante.

* Os gráficos do tipo Boxplot são excelentes ferramentas de análise de dados, principalmente para identificar _**outliers**_.

In [ ]:
import matplotlib

In [ ]:
import pandas as pd
arquivo = 'house.csv'
dataset = pd.read_csv(arquivo, sep=',', header=0)

In [ ]:
# Plota gráfico do tipo Boxplot da coluna bedrooms
# Esse gráfico é muito rico e é possível visualizar Outliers
%matplotlib notebook
matplotlib.style.use('ggplot')

dataset.boxplot(column='bedrooms')

<IPython.core.display.Javascript object>

<Axes: >

In [ ]:
# Visualizando os estilos de layout disponível
matplotlib.style.available

['Solarize_Light2',
 '_classic_test_patch',
 '_mpl-gallery',
 '_mpl-gallery-nogrid',
 'bmh',
 'classic',
 'dark_background',
 'fast',
 'fivethirtyeight',
 'ggplot',
 'grayscale',
 'seaborn-v0_8',
 'seaborn-v0_8-bright',
 'seaborn-v0_8-colorblind',
 'seaborn-v0_8-dark',
 'seaborn-v0_8-dark-palette',
 'seaborn-v0_8-darkgrid',
 'seaborn-v0_8-deep',
 'seaborn-v0_8-muted',
 'seaborn-v0_8-notebook',
 'seaborn-v0_8-paper',
 'seaborn-v0_8-pastel',
 'seaborn-v0_8-poster',
 'seaborn-v0_8-talk',
 'seaborn-v0_8-ticks',
 'seaborn-v0_8-white',
 'seaborn-v0_8-whitegrid',
 'tableau-colorblind10']

In [ ]:
# Plota boxplot da coluna 'price' por número de quartos
%matplotlib notebook
dataset.boxplot(column='price', by='bedrooms')

<IPython.core.display.Javascript object>

<Axes: title={'center': 'price'}, xlabel='bedrooms'>

**Correlação **

In [ ]:
# Imprime a correlação de todas as colunas do dataframe (person)
dataset.corr()

<ipython-input-95-b1ed171f6f41>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataset.corr()


id     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
id             1.000000 -0.016762  0.001235   0.005160    -0.012258 -0.132109   
price         -0.016762  1.000000  0.308321   0.525138     0.702035  0.089661   
bedrooms       0.001235  0.308321  1.000000   0.515929     0.576679  0.031684   
bathrooms      0.005160  0.525138  0.515929   1.000000     0.754665  0.087740   
sqft_living   -0.012258  0.702035  0.576679   0.754665     1.000000  0.172826   
sqft_lot      -0.132109  0.089661  0.031684   0.087740     0.172826  1.000000   
floors         0.018595  0.256791  0.175440   0.500626     0.353922 -0.005210   
waterfront    -0.002721  0.266369 -0.006589   0.063744     0.103818  0.021604   
view           0.011592  0.397293  0.079515   0.187737     0.284611  0.074710   
condition     -0.023783  0.036362  0.028534  -0.124982    -0.058753 -0.008958   
grade          0.008130  0.667434  0.356972   0.664983     0.762704  0.113621   
sqft_above    -0.010842  0.605567  0.477618   0.685342     0.876597  0.183512   
sqft_basement -0.005151  0.323816  0.303078   0.283770     0.435043  0.015286   
yr_built       0.021380  0.054012  0.154197   0.506019     0.318049  0.053080   
yr_renovated  -0.016907  0.126434  0.018827   0.050739     0.055363  0.007644   
zipcode       -0.008224 -0.053203 -0.152706  -0.203866    -0.199430 -0.129574   
lat           -0.001891  0.307003 -0.008963   0.024573     0.052529 -0.085683   
long           0.020799  0.021626  0.129498   0.223042     0.240223  0.229521   
sqft_living15 -0.002901  0.585379  0.391670   0.568634     0.756420  0.144608   
sqft_lot15    -0.138798  0.082447  0.029221   0.087175     0.183286  0.718557   

                 floors  waterfront      view  condition     grade  \
id             0.018595   -0.002721  0.011592  -0.023783  0.008130   
price          0.256791    0.266369  0.397293   0.036362  0.667434   
bedrooms       0.175440   -0.006589  0.079515   0.028534  0.356972   
bathrooms      0.500626    0.063744  0.187737  -0.124982  0.664983   
sqft_living    0.353922    0.103818  0.284611  -0.058753  0.762704   
sqft_lot      -0.005210    0.021604  0.074710  -0.008958  0.113621   
floors         1.000000    0.023695  0.029432  -0.263740  0.458171   
waterfront     0.023695    1.000000  0.401857   0.016653  0.082775   
view           0.029432    0.401857  1.000000   0.045990  0.251321   
condition     -0.263740    0.016653  0.045990   1.000000 -0.144674   
grade          0.458171    0.082775  0.251321  -0.144674  1.000000   
sqft_above     0.523863    0.072075  0.167649  -0.158214  0.755923   
sqft_basement -0.245708    0.080588  0.276947   0.174105  0.168392   
yr_built       0.489298   -0.026161 -0.053440  -0.361417  0.446963   
yr_renovated   0.006330    0.092885  0.103917  -0.060618  0.014414   
zipcode       -0.059093    0.030285  0.084827   0.003026 -0.184862   
lat            0.049656   -0.014274  0.006157  -0.014941  0.114084   
long           0.125399   -0.041910 -0.078400  -0.106500  0.198372   
sqft_living15  0.279856    0.086463  0.280439  -0.092824  0.713202   
sqft_lot15    -0.011280    0.030703  0.072575  -0.003406  0.119248   

               sqft_above  sqft_basement  yr_built  yr_renovated   zipcode  \
id              -0.010842      -0.005151  0.021380     -0.016907 -0.008224   
price            0.605567       0.323816  0.054012      0.126434 -0.053203   
bedrooms         0.477618       0.303078  0.154197      0.018827 -0.152706   
bathrooms        0.685342       0.283770  0.506019      0.050739 -0.203866   
sqft_living      0.876597       0.435043  0.318049      0.055363 -0.199430   
sqft_lot         0.183512       0.015286  0.053080      0.007644 -0.129574   
floors           0.523863      -0.245708  0.489298      0.006330 -0.059093   
waterfront       0.072075       0.080588 -0.026161      0.092885  0.030285   
view             0.167649       0.276947 -0.053440      0.103917  0.084827   
condition       -0.158214       0.174105 -0.361417     -0.060618  0.

In [ ]:
dataset.corr('spearman')

<ipython-input-96-d0b5e2da8657>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataset.corr('spearman')


id     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
id             1.000000  0.004178  0.006185   0.015051     0.001656 -0.116792   
price          0.004178  1.000000  0.344615   0.497160     0.644191  0.074939   
bedrooms       0.006185  0.344615  1.000000   0.521451     0.647395  0.216479   
bathrooms      0.015051  0.497160  0.521451   1.000000     0.745526  0.068805   
sqft_living    0.001656  0.644191  0.647395   0.745526     1.000000  0.304159   
sqft_lot      -0.116792  0.074939  0.216479   0.068805     0.304159  1.000000   
floors         0.018905  0.322359  0.227565   0.546776     0.401232 -0.234460   
waterfront    -0.003573  0.115089 -0.007604   0.049522     0.070326  0.085601   
view           0.012552  0.293931  0.081405   0.155549     0.232994  0.117033   
condition     -0.023969  0.018490  0.012748  -0.162891    -0.062638  0.114724   
grade          0.019835  0.658215  0.380555   0.658194     0.716400  0.152049   
sqft_above     0.003523  0.541752  0.539755   0.691006     0.843504  0.272408   
sqft_basement  0.001408  0.251704  0.230484   0.191848     0.327878  0.036624   
yr_built       0.026537  0.102038  0.180037   0.566982     0.352421 -0.037569   
yr_renovated  -0.017473  0.101876  0.016863   0.042688     0.052679  0.008536   
zipcode       -0.005359 -0.008735 -0.167202  -0.204783    -0.206848 -0.319494   
lat           -0.003732  0.456409 -0.021236   0.008283     0.030980 -0.122052   
long           0.007413  0.063537  0.191430   0.261539     0.284584  0.370551   
sqft_living15 -0.000035  0.572290  0.443878   0.570304     0.746982  0.359572   
sqft_lot15    -0.114735  0.062766  0.201530   0.063111     0.283864  0.922316   

                 floors  waterfront      view  condition     grade  \
id             0.018905   -0.003573  0.012552  -0.023969  0.019835   
price          0.322359    0.115089  0.293931   0.018490  0.658215   
bedrooms       0.227565   -0.007604  0.081405   0.012748  0.380555   
bathrooms      0.546776    0.049522  0.155549  -0.162891  0.658194   
sqft_living    0.401232    0.070326  0.232994  -0.062638  0.716400   
sqft_lot      -0.234460    0.085601  0.117033   0.114724  0.152049   
floors         1.000000    0.023876  0.019641  -0.287878  0.501672   
waterfront     0.023876    1.000000  0.284924   0.016744  0.062189   
view           0.019641    0.284924  1.000000   0.046000  0.217044   
condition     -0.287878    0.016744  0.046000   1.000000 -0.167374   
grade          0.501672    0.062189  0.217044  -0.167374  1.000000   
sqft_above     0.599258    0.054490  0.144394  -0.158126  0.711815   
sqft_basement -0.272436    0.051969  0.236525   0.161623  0.092927   
yr_built       0.551660   -0.028605 -0.066607  -0.393816  0.500633   
yr_renovated   0.012570    0.091649  0.096539  -0.066180  0.016029   
zipcode       -0.061427    0.029591  0.078215  -0.022416 -0.181552   
lat            0.024616   -0.019044 -0.000073  -0.022341  0.103921   
long           0.148640   -0.038139 -0.102728  -0.085270  0.222791   
sqft_living15  0.305398    0.074564  0.255793  -0.086905  0.662635   
sqft_lot15    -0.231411    0.092271  0.116520   0.117719  0.156109   

               sqft_above  sqft_basement  yr_built  yr_renovated   zipcode  \
id               0.003523       0.001408  0.026537     -0.017473 -0.005359   
price            0.541752       0.251704  0.102038      0.101876 -0.008735   
bedrooms         0.539755       0.230484  0.180037      0.016863 -0.167202   
bathrooms        0.691006       0.191848  0.566982      0.042688 -0.204783   
sqft_living      0.843504       0.327878  0.352421      0.052679 -0.206848   
sqft_lot         0.272408       0.036624 -0.037569      0.008536 -0.319494   
floors           0.599258      -0.272436  0.551660      0.012570 -0.061427   
waterfront       0.054490       0.051969 -0.028605      0.091649  0.029591   
view             0.144394       0.236525 -0.066607      0.096539  0.078215   
condition       -0.158126       0.161623 -0.393816     -0.066180 -0.

In [ ]:
# Imprime a correlação de spearman (esta leva em consideração a correção positiva e negativa)
dataset.corr('spearman')

<ipython-input-97-ee8da6c96034>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataset.corr('spearman')


id     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
id             1.000000  0.004178  0.006185   0.015051     0.001656 -0.116792   
price          0.004178  1.000000  0.344615   0.497160     0.644191  0.074939   
bedrooms       0.006185  0.344615  1.000000   0.521451     0.647395  0.216479   
bathrooms      0.015051  0.497160  0.521451   1.000000     0.745526  0.068805   
sqft_living    0.001656  0.644191  0.647395   0.745526     1.000000  0.304159   
sqft_lot      -0.116792  0.074939  0.216479   0.068805     0.304159  1.000000   
floors         0.018905  0.322359  0.227565   0.546776     0.401232 -0.234460   
waterfront    -0.003573  0.115089 -0.007604   0.049522     0.070326  0.085601   
view           0.012552  0.293931  0.081405   0.155549     0.232994  0.117033   
condition     -0.023969  0.018490  0.012748  -0.162891    -0.062638  0.114724   
grade          0.019835  0.658215  0.380555   0.658194     0.716400  0.152049   
sqft_above     0.003523  0.541752  0.539755   0.691006     0.843504  0.272408   
sqft_basement  0.001408  0.251704  0.230484   0.191848     0.327878  0.036624   
yr_built       0.026537  0.102038  0.180037   0.566982     0.352421 -0.037569   
yr_renovated  -0.017473  0.101876  0.016863   0.042688     0.052679  0.008536   
zipcode       -0.005359 -0.008735 -0.167202  -0.204783    -0.206848 -0.319494   
lat           -0.003732  0.456409 -0.021236   0.008283     0.030980 -0.122052   
long           0.007413  0.063537  0.191430   0.261539     0.284584  0.370551   
sqft_living15 -0.000035  0.572290  0.443878   0.570304     0.746982  0.359572   
sqft_lot15    -0.114735  0.062766  0.201530   0.063111     0.283864  0.922316   

                 floors  waterfront      view  condition     grade  \
id             0.018905   -0.003573  0.012552  -0.023969  0.019835   
price          0.322359    0.115089  0.293931   0.018490  0.658215   
bedrooms       0.227565   -0.007604  0.081405   0.012748  0.380555   
bathrooms      0.546776    0.049522  0.155549  -0.162891  0.658194   
sqft_living    0.401232    0.070326  0.232994  -0.062638  0.716400   
sqft_lot      -0.234460    0.085601  0.117033   0.114724  0.152049   
floors         1.000000    0.023876  0.019641  -0.287878  0.501672   
waterfront     0.023876    1.000000  0.284924   0.016744  0.062189   
view           0.019641    0.284924  1.000000   0.046000  0.217044   
condition     -0.287878    0.016744  0.046000   1.000000 -0.167374   
grade          0.501672    0.062189  0.217044  -0.167374  1.000000   
sqft_above     0.599258    0.054490  0.144394  -0.158126  0.711815   
sqft_basement -0.272436    0.051969  0.236525   0.161623  0.092927   
yr_built       0.551660   -0.028605 -0.066607  -0.393816  0.500633   
yr_renovated   0.012570    0.091649  0.096539  -0.066180  0.016029   
zipcode       -0.061427    0.029591  0.078215  -0.022416 -0.181552   
lat            0.024616   -0.019044 -0.000073  -0.022341  0.103921   
long           0.148640   -0.038139 -0.102728  -0.085270  0.222791   
sqft_living15  0.305398    0.074564  0.255793  -0.086905  0.662635   
sqft_lot15    -0.231411    0.092271  0.116520   0.117719  0.156109   

               sqft_above  sqft_basement  yr_built  yr_renovated   zipcode  \
id               0.003523       0.001408  0.026537     -0.017473 -0.005359   
price            0.541752       0.251704  0.102038      0.101876 -0.008735   
bedrooms         0.539755       0.230484  0.180037      0.016863 -0.167202   
bathrooms        0.691006       0.191848  0.566982      0.042688 -0.204783   
sqft_living      0.843504       0.327878  0.352421      0.052679 -0.206848   
sqft_lot         0.272408       0.036624 -0.037569      0.008536 -0.319494   
floors           0.599258      -0.272436  0.551660      0.012570 -0.061427   
waterfront       0.054490       0.051969 -0.028605      0.091649  0.029591   
view             0.144394       0.236525 -0.066607      0.096539  0.078215   
condition       -0.158126       0.161623 -0.393816     -0.066180 -0.

In [ ]:
# Imprime a correção de algumas colunas
dataset[['bedrooms','bathrooms','floors','grade','price']].corr()

bedrooms  bathrooms    floors     grade     price
bedrooms   1.000000   0.515929  0.175440  0.356972  0.308321
bathrooms  0.515929   1.000000  0.500626  0.664983  0.525138
floors     0.175440   0.500626  1.000000  0.458171  0.256791
grade      0.356972   0.664983  0.458171  1.000000  0.667434
price      0.308321   0.525138  0.256791  0.667434  1.000000

# Fim

## Valeu!

### #Instagram - Ciencia dos Dados <a href="http://instagram.com/cienciadosdados">instagram.com/cienciadosdados</a>